site_name: MPB Documentation
site_author: S. G. Johnson et al.
repo_url: https://github.com/stevengj/mpb/

docs_dir: 'doc/docs'
site_dir: 'doc/site'

theme_dir: 'doc/mpb-mkdocs-theme'
theme: readthedocs

python:
   version: 2 # for unicode
   setup_py_install: True

markdown_extensions:
    - wikilinks
    - toc:
        title: Table of Contents
    - attr_list
    - fenced_code
    - mdx_math:
        enable_dollar_delimiter: True

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']

pages:
 - MIT_Photonic_Bands.md
 - MPB_download.md
 - MPB_release_notes.md
 - Citing_MPB.md
 - MPB_manual.md
 - MPB_Introduction.md
 - MPB_Installation.md
 - MPB_User_Tutorial.md
 - MPB_Data_Analysis_Tutorial.md
 - MPB_User_Reference.md
 - MPB_Developer_Information.md
 - MPB_Acknowledgements.md
 - MPB_License_and_Copyright.md
 - MPB_on_Debian.md
 - MPB_tutorial.md
 - The_MPB_Manual.md
 - The_run_function_is_not_a_loop.md
